name: Feature request
description: Suggest an improvement to the app or code
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea
  - type: checkboxes
    id: help
    attributes:
      label: Contribution
      options:
        - label: I would like to work on this
